<?php
/*
 * Created on : Sep 28, 2017, 9:10:03 AM
 * Author: Tran Trong Thang
 * Email: trantrongthang1207@gmail.com
 * Skype: trantrongthang1207
 */
$tips = $this->getProduct()->getTips();
?>
<div class="em-block-title"><h2><?php echo $this->__('Tips') ?></h2></div>
<div class="box-collateral-content">
    <div class="std">
        <?php echo $this->helper('catalog/output')->productAttribute($this->getProduct(), $tips, 'tips') ?>
    </div>
</div>
